### ISSUE TITLE
Set predefined permissions at resource creation

### ISSUE THREAD

**Issue by nicolas-bonnel** [koumoul-dev/data-fair#46]
For each type of resource (datasets, remote-services and applications), we should be able to configure a predefined set of permissions. This set would be stored in user or organizations settings.

For instance an organization could be able to make all its datasets publicly readeable once they are created.

**Comment by albanm** [comment]
I have other ideas for evolving permissions:

  - set permissions globally for all resources of a collection as well as by resource (for example : this user can read all my datasets, or can use all my remote services)
  - associate quotas to read permissions (for example public = 1mo, orga1 = 100mo and myself = unlimited). I prefer this rather than the predefined sets of permissions applied to all resources.
  - store consumptions stats (with a defined life time), so you can know who uses which datasets/service
  - also add columns and lines filters
